name: Lint and Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
        - name: Clone codebase
          uses: actions/checkout@v2

        - name: Setup node
          uses: actions/setup-node@v2
          with:
            node-version: 16

        - name: Yarn cache
          uses: actions/cache@v2
          id: yarn-cache
          with:
            path: |
              .yarn/cache
            key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-

        - name: Install project dependencies
          run: yarn install

        - name: Lint
          run: yarn lint

        - name: Test
          run: yarn test